### PR TITLE
Do not use program data in Beats MSI installers

### PR DESCRIPTION
**Pull request by cmacknz**
Store configuration, runtime, and log data in ProgramFiles.

### CODE REVIEW

**Comment by cmacknz** [comment]
buildkite test it

**Review by amitkanfer — DISMISSED** [review]
LGTM

**Comment by cmacknz** [comment]
Buildkite doesn't actually seem to be running for this branch, hmm. https://buildkite.com/elastic/elastic-stack-installers

**Comment by dliappis** [comment]
> Buildkite doesn't actually seem to be running for this branch, hmm. https://buildkite.com/elastic/elastic-stack-installers

@cmacknz this is expected, to be fixed by https://github.com/elastic/elastic-stack-installers/pull/235 ; for now just use "Merge without waiting for requirements to be met (bypass branch protections)"

**Comment by cmacknz** [comment]
For users that are using the MSI to upgrade Beats in place, this will be a breaking change because the local Filebeat/Winlogbeat/etc registries are discarded. This will cause previously invested data to be ingested again.

**Comment by dliappis** [comment]
buildkite test this

**Comment by cmacknz** [comment]
Closing in favor of https://github.com/elastic/elastic-stack-installers/pull/238

**Pull request closed without merging**
