### PR TITLE
Create a buildkite pipeline to replace Jenkins

### PR DESCRIPTION
**Pull request by alpar-t**
This pipeline replaced the existing jenkins one defined here. 
It doesn't do much, but is equivalent to the one in Jenkins. 
The next step is to grab the script from the RM and add it here in a follow up PR and upload artefacts.

Rel https://github.com/elastic/release-eng/issues/529

### CODE REVIEW

**Comment by alpar-t** [comment]
Fun fact: this was my first windows pipeline and I think the first one that passed on the first try. I was going to head over to #ci-systems to tell them that BK pipelines are not running when I first saw the green tick on this PR

**Comment by alpar-t** [comment]
The Jenkins pipeline had a slack notification to a non existing room, so I'm not replicating this

**Review by jmlrt — COMMENTED** [review]
Nice 👍🏻 

> The Jenkins pipeline had a slack notification to a non existing room, so I'm not replicating this

I think this should go to `#release-eng-alerts`.

Also the jobs for 8.6 and master branch used to be triggered daily, not sure if we are fine with builds only on commit or want to keep up with a cron schedule => weekly instead of daily would surely be enough regarding the repository (lack of) activity.

**Comment by alpar-t** [comment]
Sounds good! @jmlrt  I'm not closing the linked issue, let's do them in a follow up

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Pull request merged**
