### PR TITLE
Allow pipeline to run on 8.x branch

### PR DESCRIPTION
**Pull request by jlind23**

### CODE REVIEW

**Review by dliappis — COMMENTED** [review]
I think we need to adjust the regex also in https://github.com/elastic/elastic-stack-installers/blob/372cbc75cdb9ea3fe925980c23a3876f717aa85f/.buildkite/scripts/build.ps1#L4 ?

**Comment by jlind23** [comment]
@dliappis you are right, fixed.

**Review by dliappis — APPROVED** [review]
LGTM

the failure is that https://snapshots.elastic.co/latest/8.x.json is missing which I guess is true right now (chicken and egg problem).

**Comment by jlind23** [comment]
Merging this. Will wait for the first 8.x unified release to take place now.

**Pull request merged**
